name: hinatest
type: service
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: python hello_world.py
    python_version: '3.11'
    build_context_path: ./
  # `build_source.branch_name` and `build_source.ref` will automatically be patched during deployment.
  build_source:
    ref: e70a4abbf40afe7c74a49d2046ddb0238eb66529
    type: git
    repo_url: https://github.com/hinamurdhani/hinatestrepo
    branch_name: main
ports:
  - host: hinatest-hinaworkspace-3000.develop.truefoundry.tech
    port: 3000
    expose: true
    protocol: TCP
    app_protocol: http
replicas: 1
resources:
  node:
    type: node_selector
    capacity_type: spot_fallback_on_demand
  cpu_limit: 0.5
  cpu_request: 0.2
  memory_limit: 500
  memory_request: 200
  ephemeral_storage_limit: 2000
  ephemeral_storage_request: 1000
workspace_fqn: tfy-usea1-develop:hinaworkspace
allow_interception: false